const productos = [
    {
        "id": 1 ,
        "nombre": "Meta Quest 1",
        "precio": 299.99,
        "stock": 25,
        "descripcion": "El Meta Quest 1 es un dispositivo de realidad virtual todo en uno desarrollado por Meta. No requiere cables ni PC para funcionar, ofreciendo una experiencia inmersiva y completa.",
        "imagenes": ["./IMG/metaQuest1_img1.jpg","./IMG/metaQuest1_img2.jpg","./IMG/metaQuest1_img3.jpg","./IMG/metaQuest1_img4.jpg"],
        "tiempos_entrega_envio": "3-5 días hábiles, gastos de envío incluidos",
        "opciones_entrega": "Entrega a domicilio",
        "garantia": "1 año",
        "resena_usuarios": 4
    },
    {
        "id": 2 ,
        "nombre": "Meta Quest 2",
        "precio": 399.99,
        "stock": 30,
        "descripcion": "Meta Quest 2 ofrece una resolución más alta y un rendimiento mejorado en comparación con su predecesor. Es un visor de realidad virtual todo en uno que no requiere PC ni cables.",
        "imagenes": ["./IMG/metaQuest2_img1.jpg","./IMG/metaQuest2_img2.jpg","./IMG/metaQuest2_img3.jpg","./IMG/metaQuest2_img4.jpg"],
        "tiempos_entrega_envio": "3-5 días hábiles, gastos de envío incluidos",
        "opciones_entrega": "Entrega a domicilio",
        "garantia": "2 años",
        "resena_usuarios": 5
    },
    {
        "id": 3 ,
        "nombre": "Meta Quest 3",
        "precio": 499.99,
        "stock": 20,
        "descripcion": "El Meta Quest 3 es la última versión de la línea Quest, con una mayor resolución, mejor procesamiento y nuevas características para una experiencia de realidad virtual superior.",
        "imagenes":["./IMG/metaQuest3_img1.jpg","./IMG/metaQuest3_img2.jpg","./IMG/metaQuest3_img3.jpg","./IMG/metaQuest3_img4.jpg"],
        "tiempos_entrega_envio": "3-5 días hábiles, gastos de envío incluidos",
        "opciones_entrega": "Entrega a domicilio",
        "garantia": "2 años",
        "resena_usuarios": 5
    },
    {
        "id": 4 ,
        "nombre": "Meta Quest Pro",
        "precio": 899.99,
        "stock": 15,
        "descripcion": "Meta Quest Pro es el visor más avanzado de Meta, diseñado para profesionales y entusiastas de la realidad virtual que buscan el mejor rendimiento y calidad.",
        "imagenes": ["./IMG/metaQuestPro_img1.jpg","./IMG/metaQuestPro_img2.jpg","./IMG/metaQuestPro_img3.jpg","./IMG/metaQuestPro_img4.jpg"],
        "tiempos_entrega_envio": "3-5 días hábiles, gastos de envío incluidos",
        "opciones_entrega": "Entrega a domicilio",
        "garantia": "2 años",
        "resena_usuarios": 5
    },
    {
        "id": 5 ,
        "nombre": "HTC VIVE Pro 2",
        "precio": 1371.02,
        "stock": 18,
        "descripcion": "El HTC VIVE Pro 2 es un visor de realidad virtual de alta calidad que ofrece seguimiento preciso y una experiencia inmersiva completa, ideal para juegos y aplicaciones profesionales.",
        "imagenes": ["./IMG/HTCVivePro2_img1.jpg","./IMG/HTCVivePro2_img2.jpg","./IMG/HTCVivePro2_img3.jpg","./IMG/HTCVivePro2_img4.jpg"],
        "tiempos_entrega_envio": "3-5 días hábiles, gastos de envío incluidos",
        "opciones_entrega": "Entrega a domicilio",
        "garantia": "1 año",
        "resena_usuarios": 4
    },
    {
        "id": 6 ,
        "nombre": "Valve Index",
        "precio": 999.99,
        "stock": 10,
        "descripcion": "Valve Index es uno de los visores de realidad virtual más avanzados, conocido por su alta resolución, frecuencia de actualización rápida y controles avanzados.",
        "imagenes": ["./IMG/ValveIndex_img1.jpg","./IMG/ValveIndex_img2.jpg","./IMG/ValveIndex_img3.jpg","./IMG/ValveIndex_img4.jpg"],
        "tiempos_entrega_envio": "3-5 días hábiles, gastos de envío incluidos",
        "opciones_entrega": "Entrega a domicilio",
        "garantia": "2 años",
        "resena_usuarios": 5
    },
    {
        "id": 7 ,
        "nombre": "Pico 4",
        "precio": 499.99,
        "stock": 22,
        "descripcion": "Pico 4 es un visor de realidad virtual autónomo que ofrece una experiencia inmersiva con una alta resolución y un diseño ligero y cómodo.",
        "imagenes": ["./IMG/Pico4_img1.jpg","./IMG/Pico4_img2.jpg","./IMG/Pico4_img3.png","./IMG/Pico4_img4.jpg"],
        "tiempos_entrega_envio": "3-5 días hábiles, gastos de envío incluidos",
        "opciones_entrega": "Entrega a domicilio",
        "garantia": "1 año",
        "resena_usuarios": 4
    },
    {
        "id": 8 ,
        "nombre": "VIVE Tracker",
        "precio": 149.99,
        "stock": 35,
        "descripcion": "Trackers de cuerpo completo que permiten un seguimiento preciso de los movimientos del cuerpo para una experiencia de realidad virtual más inmersiva y realista.",
        "imagenes": ["./IMG/VIVETracker_img1.jpg","./IMG/VIVETracker_img2.jpg","./IMG/VIVETracker_img3.jpg","./IMG/VIVETracker_img4.jpg"],
        "tiempos_entrega_envio": "3-5 días hábiles, gastos de envío incluidos",
        "opciones_entrega": "Entrega a domicilio",
        "garantia": "1 año",
        "resena_usuarios": 4
    },
    {
        "id": 9 ,
        "nombre": "Mandos adicionales para Meta Quest",
        "precio": 79.99,
        "stock": 40,
        "descripcion": "Mandos adicionales para Meta Quest, diseñados para ofrecer un control preciso y una interacción intuitiva en la realidad virtual.",
        "imagenes": ["./IMG/MandosQuest2_img1.jpg","./IMG/MandosQuest2_img2.jpg","./IMG/MandosQuest2_img3.jpg","./IMG/MandosQuest2_img4.jpg"],
        "tiempos_entrega_envio": "3-5 días hábiles, gastos de envío incluidos",
        "opciones_entrega": "Entrega a domicilio",
        "garantia": "1 año",
        "resena_usuarios": 4
    },
    {
        "id": 10 ,
        "nombre": "Funda rígida de transporte compatible con Meta Quest 3/Quest 2/Vision Pro",
        "precio": 19.99,
        "stock": 50,
        "descripcion": "Funda de diseño patentado para Meta Quest 3, Quest 2 y Vision Pro. Esta funda de transporte rígida está especialmente diseñada para Meta Quest 3, Quest 2 y Vision Pro. No es compatible con la correa Elite ni con otras trampas para la cabeza de terceros con batería.",
        "imagenes": ["./IMG/Estuche_img1.jpg","./IMG/Estuche_img2.jpg","./IMG/Estuche_img3.jpg","./IMG/Estuche_img4.jpg"],
        "tiempos_entrega_envio": "3-5 días hábiles, gastos de envío incluidos",
        "opciones_entrega": "Entrega a domicilio",
        "garantia": "1 año",
        "resena_usuarios": 5
    },
    {
        "id": 11 ,
        "nombre": "Base de carga para mandos VR",
        "precio": 54.99,
        "stock": 45,
        "descripcion": "Base de carga para mandos de realidad virtual, permite cargar fácilmente tus mandos y mantenerlos organizados.",
        "imagenes": ["./IMG/BaseCarga_img1.jpg","./IMG/BaseCarga_img2.jpg","./IMG/BaseCarga_img3.jpg","./IMG/BaseCarga_img4.jpg"],
        "tiempos_entrega_envio": "3-5 días hábiles, gastos de envío incluidos",
        "opciones_entrega": "Entrega a domicilio",
        "garantia": "1 año",
        "resena_usuarios": 4
    },
    {
        "id": 12 ,
        "nombre": "Correa rigida BOBOVR M2 ",
        "precio": 89.99,
        "stock": 50,
        "descripcion": "BOBOVR M2  es compatible con Quest 2. BOBOVR M2 ofrece una comodidad y ajustabilidad mejorada para sesiones de juego más agradables ",
        "imagenes": ["./IMG/BOBOVRM2_img1.jpg","./IMG/BOBOVRM2_img2.jpg","./IMG/BOBOVRM2_img3.jpg","./IMG/BOBOVRM2_img4.jpg"],
        "tiempos_entrega_envio": "3-5 días hábiles, gastos de envío incluidos",
        "opciones_entrega": "Entrega a domicilio",
        "garantia": "18 meses",
        "resena_usuarios": 5,
    }
]
